# Generated by Django 4.2.1 on 2023-05-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='d_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.CharField(max_length=255)),
                ('new_image', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
            ],
        ),
    ]
